### ISSUE TITLE
As a developer, I'd like to be able to view a CHANGELOG.md for changes made at each release of the reporter.

### ISSUE THREAD

**Issue by julmot** [tmcgee123/karma-spec-reporter#54]
The release description doesn't contain information about changes. So a changelog is necessary.

**Comment by felquis** [comment]
:+1: this would be good for tracking breaking changes

I'm at version 0.0.10, I'm not sure what was updated to the current 0.0.26

**Comment by tmcgee123** [comment]
No breaking changes ever in the history of this reporter. Closing for now
