### ISSUE TITLE
As a Developer, I would like the status characters (- or x) to be highlighted so that I can easily tell them apart from the failure message

### ISSUE THREAD

**Issue by alexanderbird** [tmcgee123/karma-spec-reporter#66]
I know it's a minor thing, but it would be nice if the status characters stood out more so when I visually scan the results I can quickly identify the start of each failure message. As it is, the 'x' seems to blend in with the failure message. 

The success indicator isn't such an issue, because √ doesn't look like a regular character, unlike x. Still, it would be nice if it was green. 

Example of the sort of test output I'm talking about:
```
 ClassName
    General category
      MethodName
        × has the expected value when stuff happens (1ms)
        Expected 'bad value' to equal 'expected value'.
        stack trace....
```
I have a few ideas of how this could be done (in order of decreasing preference)
## Idea 1: color
If the x was colored in a way that stands out. This could be added as a config option: colors.success, colors.skipped, and colors.failure. 

## Idea 2: indentation
Change the indentation so that the 'x's stand out more
```
 ClassName
    General category
      MethodName
        ×  has the expected value when stuff happens (1ms)
           Expected 'bad value' to equal 'expected value'.
           stack trace....
```
Note: this is already the case for successful tests, since there is no error detail below. 
```
  ClassName
    Method
      √ does good stuff in the happy case (25ms)
      √ does good stuff in such and such a corner case (10ms)
      √ does the right bad stuff when such and such a precondition isn't met (12ms)
```

So aligning the error details with the test description rather than with the status indicator character might be the most consistent way. 

## Idea 3: square brackets
Actually I don't really like this idea, but basically it's changing the status character from 'x' to '[x]' so that it doesn't look like a regular character. The first two ideas seem much nicer to me. 
```
 ClassName
    General category
      MethodName
        [×] has the expected value when stuff happens (1ms)
        Expected 'bad value' to equal 'expected value'.
        stack trace....
```

**Comment by tmcgee123** [comment]
@alexanderbird have you try passing the color option to the reporter? That should give you some type of way to apply to your Idea 1

**Comment by sarathkcm** [comment]
It would be nice to have the status characters configurable. 
Something like:
```json
{
   "failedIndicator" : "[x]",
   "successIndicator": "*",
   "skippedIndicator": "!"
} 
```

It appears that my CI server has trouble reading the default status characters which karma-spec-reporter prints, and therefore the test run logs don't look very pretty.

**Comment by sarathkcm** [comment]
Just went through the source code now. It looks like it is already configurable through 'prefixes' configuration option. It would be nice to add this to the docs.

**Comment by tmcgee123** [comment]
Closing with @sarathkcm comments
