### ISSUE TITLE
Reports "SUCCESS" instead of "DISCONNECTED"

### ISSUE THREAD

**Issue by Narretz** [tmcgee123/karma-spec-reporter#69]
I just added this reporter to the main AngularJS project, and it's looking really nice. However, I think there's a bug in the overall report, i.e. at the end of each run when the passed / failed / overall tests are counted. A specific browser disconnected and only ran a part of the tests. However, the spec-reporter writes "SUCCESS" in the overall report.
See https://travis-ci.org/angular/angular.js/jobs/241613711#L779

**Comment by tmcgee123** [comment]
I'm not sure what the bug is, it looks like it still ran the tests all the way through, except for firefox:
Firefox 47.0.0 (Windows 7 0.0.0): Executed 650 of 1374 SUCCESS (0 secs / 4.396 secs)

So, it looks like it was able to run 650 tests successfully out of 1374, and 11494 total tests successfully. Is that correct?

````
Chrome 51.0.2704 (Windows 7 0.0.0): Executed 1400 of 1400 SUCCESS (8.5 secs / 8.267 secs)
IE 11.0.0 (Windows 8.1 0.0.0): Executed 1374 of 1374 SUCCESS (20.357 secs / 20.21 secs)
IE 10.0.0 (Windows 8 0.0.0): Executed 1374 of 1374 SUCCESS (23.639 secs / 23.454 secs)
Firefox 47.0.0 (Windows 7 0.0.0): Executed 650 of 1374 SUCCESS (0 secs / 4.396 secs)
IE 9.0.0 (Windows 7 0.0.0): Executed 1161 of 1161 SUCCESS (24.719 secs / 24.022 secs)
Safari 9.1.2 (Mac OS X 10.11.6): Executed 1374 of 1374 SUCCESS (12.098 secs / 12.374 secs)
Safari 8.0.8 (Mac OS X 10.10.5): Executed 1374 of 1374 SUCCESS (15.493 secs / 15.057 secs)
Edge 14.14393.0 (Windows 10 0.0.0): Executed 1399 of 1399 SUCCESS (14.601 secs / 14.496 secs)
Mobile Safari 8.0.0 (iOS 10.10.5): Executed 1388 of 1388 SUCCESS (16.632 secs / 16.479 secs)
TOTAL: 11494 SUCCESS
````

**Comment by Narretz** [comment]
It's correct that it ran 650 tests successfully and then FF disconnected. This was on Saucelabs via Travis. You can see this further up in the log. To clarify - that the tests didn't finish has nothing to do with the reporter.
I think it should say disconnected because that's what the dots reporter says at this point. I think it's incorrect to say success because it hasn't been able to run all tests

**Comment by Narretz** [comment]
To clarify again, it should say disconnected only for Firefox at this point. Overall it's debatable what the status should be.

**Comment by tmcgee123** [comment]
No value other than the label saying disconnected. Closing for now
