### ISSUE TITLE
Colors still appearing in output messaging when disabled

### ISSUE THREAD

**Issue by walteranderson** [tmcgee123/karma-spec-reporter#71]
Hi there,

When I have `colors: false` in my karma configuration, I would expect any colors used in this reporter to also disable. However, when a test fails I am still seeing the failed test appear in red and grey. This doesn't work particularly well with my terminal color scheme, which causes the stack trace to disappear since the background is the same grey color being used in the output message.

It appears related to the `logFinalErrors` function. Here's a snippet of the code where I believe the problem is occurring.

```
      this.writeCommonMsg((index + ') ' + failure.description + '\n').red); << here
      this.writeCommonMsg((this.WHITESPACE + failure.suite.join(' ') + '\n').red); << here
      failure.log.forEach(function (log) {
        if (reporterCfg.maxLogLines) {
          log = log.split('\n').slice(0, reporterCfg.maxLogLines).join('\n');
        }
        this.writeCommonMsg(this.WHITESPACE + formatError(log)
            .replace(/\\n/g, '\n').grey); << here
      }, this);
```

You can see the `.red` and `.grey` appended to the string being passed to `writeCommonMsg`.

Any help here would be appreciated.

**Comment by tmcgee123** [comment]
This will be fixed soon. Hella late but hey what the heck
