### ISSUE TITLE
Take browserConsoleLogOptions.level into consideration

### ISSUE THREAD

**Issue by guilhermevrs** [tmcgee123/karma-spec-reporter#74]
Hey
I was wondering if we could include the use of browserConsoleLogOptions.level to check if the log level is higher than the one set

I believe it should be something around here: https://github.com/mlex/karma-spec-reporter/blob/master/index.js#L126-L135

This would enable us to suppress the info and warning messages for example but keep the errors

Cheers

**Comment by tmcgee123** [comment]
This will be done soon, thank you for providing the code that really helps!
