### ISSUE TITLE
Fail Fast option doesn't stop build

### ISSUE THREAD

**Issue by alisa-duncan** [tmcgee123/karma-spec-reporter#77]
Our build npm script concatenates multiple npm commands including running unit tests.

When `failFast` option is enabled, if there is a failing unit test, the unit tests terminate it doesn't stop the build and continues to the next npm command (running e2e tests). If I disable `failFast`, the build terminates as expected at the end of the unit test command.

It looks like karma-spec-reporter throws an error if `failFast` is enabled. Does this emit the same ERROR signal as a failing test without the `failFast` enabled?

I am using the following versions of packages and Angular v6:
```
"karma": "~1.7.1",
"karma-chrome-launcher": "~2.2.0",
"karma-coverage-istanbul-reporter": "~1.4.2",
"karma-jasmine": "~1.1.1",
"karma-jasmine-html-reporter": "^0.2.2",
"karma-junit-reporter": "^1.2.0",
"karma-spec-reporter": "0.0.32",
```

**Comment by tmcgee123** [comment]
This is expected behavior, closing for now
