### ISSUE TITLE
Show object diff when chai deepEqual fails - feature request

### ISSUE THREAD

**Issue by lusarz** [tmcgee123/karma-spec-reporter#78]
When an assertion using deep.equals fails, it would be nice to get a detailed output that shows
 piece by piece what is different between the expected and actual values. Something like:

![deep-equals-diff](https://user-images.githubusercontent.com/10059264/42418441-c512a980-82a0-11e8-9c5a-e7745c0b6fa5.png)

**Comment by lusarz** [comment]
Sure:
https://github.com/chaijs/deep-eql

`karma-mocha-reporter` has this feature implemented:
https://github.com/litixsoft/karma-mocha-reporter/blob/master/index.js#L373
so it may be good inspiration point.

**Comment by tmcgee123** [comment]
Would you be willing to put a PR up? There is a little bit of work since we enforce TDD. Thanks for the help, I haven't had as much time to contribute recently. I'm still surprised with the amount of people using this since Webpack is the "future".

**Comment by tmcgee123** [comment]
Closing as this is old and only one person has commented. Will re-open if someone else requests it or if they have a PR ready to go
